### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by hcarreras** [PartidoDeInternet/AgoraOnRails#64]
Hi,

I have some errors we I run the code, I don't know if it just me, can anyway test?

The first error is:

 1) Admin can close proposals
  In order to finish an opened proposal
  As an admin
  I want to close a proposal
 User cannot finish a proposal

```
Failure/Error: page.should have_content("You are being redirected")
     Capybara::ElementNotFound:
       Unable to find xpath "/html"
     # ./spec/acceptance/admin_can_close_proposals_spec.rb:46:in `block (2 levels) in <top (required)>'
```

I found some information about what problem can be:
https://groups.google.com/forum/#!topic/ruby-capybara/PDr7sZ124Vw

Second error:

2)
  In order to have up-to-date proposals
  As an admin
  I want to update the proposals through congress-api
 update proposals through the congress-api

```
Failure/Error: proposal.official_url.should  ==  "http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Busqueda%20Avanzada?_piref73_1335465_73_1335464_1335464.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW10&PIECE=IWA0&FMT=INITXD1S.fmt&FORM1=INITXLTS.fmt&DOCS=29-29&QUERY=%28I%29.ACIN1.+%26+%28%22COMPETENCIA+LEGISLATIVA+PLENA%22%29.TPTR."
       expected: "http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Busqueda%20Avanzada?_piref73_1335465_73_1335464_1335464.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW10&PIECE=IWA0&FMT=INITXD1S.fmt&FORM1=INITXLTS.fmt&DOCS=29-29&QUERY=%28I%29.ACIN1.+%26+%28%22COMPETENCIA+LEGISLATIVA+PLENA%22%29.TPTR."
            got: "http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Busqueda%20Avanzada?_piref73_1335465_73_1335464_1335464.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW10&PIECE=IWA0&FMT=INITXD1S.fmt&FORM1=INITXLTS.fmt&DOCS=32-32&QUERY=%28I%29.ACIN1.+%26+%28%22COMPETENCIA+LEGISLATIVA+PLENA%22%29.TPTR." (using ==)
     # ./spec/acceptance/update_proposals_through_api_spec.rb:24:in `block (2 levels) in <top (required)>'
```

But they looks quite the same...

Thanks!

**Comment by voodoorai2000** [comment]
Cheers! 

Fixed
https://github.com/PartidoDeInternet/AgoraOnRails/commit/cb4e81f4ed6f6d61382f07f99f08d535d34fc853#diff-6be4b6d3152137c19e5f40cac626867fL43
